import tkinter as tk
from tkinter import font as tkfont

# Flashcards based on the provided Q&A pairs
flashcards = [
    # Chapter 6
    ("According to Erik Erikson, what is the primary psychosocial task of early childhood in the initiative versus guilt stage?", 
     "The primary task is developing initiative, where children take on new challenges and assert themselves."),
    ("How does self-understanding contribute to a child’s development during Erikson's initiative versus guilt stage?", 
     "Self-understanding helps children recognize their abilities and limits, fostering confidence and autonomy."),
    ("How does understanding others contribute to a child’s development during Erikson's initiative versus guilt stage?", 
     "Understanding others promotes empathy, social skills, and cooperative play, reducing guilt from social missteps."),
    ("In Piaget’s heteronomous morality stage, how do children understand rules?", 
     "Children see rules as fixed, unchangeable, and imposed by authority figures."),
    ("In Piaget’s heteronomous morality stage, how do children understand intentions and punishment?", 
     "Intentions are ignored; punishment is based on consequences, often seen as automatic and severe."),
    ("In Piaget’s autonomous morality stage, how do children understand rules?", 
     "Children view rules as flexible, created by people, and changeable through agreement."),
    ("In Piaget’s autonomous morality stage, how do children understand intentions and punishment?", 
     "Intentions matter more than outcomes; punishment should fit the intent and be fair."),
    ("What role do peer relations play in advancing children's moral reasoning according to Piaget?", 
     "Peers provide opportunities for negotiation, perspective-taking, and challenging egocentric views."),
    ("What role do caregivers play in advancing children's moral reasoning according to Piaget?", 
     "Caregivers model fairness, explain intentions, and encourage discussion to shift from heteronomous to autonomous morality."),
    ("How do social influences like parents and peers explain children's gender identity development?", 
     "Parents and peers reinforce gender-typical behaviors through modeling, rewards, and social interactions."),
    ("How does gender schema theory (a cognitive theory) explain children's gender identity development?", 
     "Children form schemas organizing information by gender, influencing how they perceive and adopt gender roles."),
    ("How does social role theory explain children's gender identity and roles?", 
     "It emphasizes societal expectations and divisions of labor that shape gender behaviors from early childhood."),
    ("How does psychoanalytic theory explain children's gender identity development?", 
     "Through identification with the same-sex parent during the phallic stage to resolve Oedipus/Electra complexes."),
    ("How does social cognitive theory explain children's gender identity development?", 
     "Through observation, imitation, and reinforcement of gender behaviors from models like parents and media."),
    ("What are the key features of Baumrind’s authoritarian parenting style?", 
     "High demands, low responsiveness; strict rules, punishment-focused, little warmth."),
    ("What effects does authoritarian parenting have on children’s development?", 
     "Often leads to obedience but also anxiety, low self-esteem, and poor social skills."),
    ("What are the key features of Baumrind’s authoritative parenting style?", 
     "High demands, high responsiveness; clear rules with explanations, warmth, and support."),
    ("What effects does authoritative parenting have on children’s development?", 
     "Promotes competence, self-regulation, high self-esteem, and positive social outcomes."),
    ("What are the key features of Baumrind’s neglectful parenting style?", 
     "Low demands, low responsiveness; uninvolved, little guidance or emotional support."),
    ("What effects does neglectful parenting have on children’s development?", 
     "Linked to poor self-control, low achievement, delinquency, and emotional issues."),
    ("What are the key features of Baumrind’s indulgent parenting style?", 
     "Low demands, high responsiveness; permissive, few rules, high warmth but little structure."),
    ("What effects does indulgent parenting have on children’s development?", 
     "Can lead to impulsivity, poor self-discipline, and entitlement, but sometimes high self-esteem."),
    ("What do research findings suggest about cultural context in parenting styles?", 
     "Authoritative style is generally positive across cultures, but authoritarian may be less harmful in collectivist cultures."),
    ("What do research findings suggest about punishment practices in shaping children’s outcomes?", 
     "Harsh physical punishment links to aggression and poor emotional regulation; consistent, mild discipline is better."),
    ("What do research findings suggest about coparenting in shaping children’s outcomes?", 
     "Supportive coparenting (cooperation between parents) promotes secure attachment and better social-emotional development."),

    # Chapter 7
    ("What developmental stage does Chapter 7 cover?", 
     "Middle and late childhood, bridging early childhood and adolescence."),
    ("Why is middle and late childhood called the 'calm before the storm'?", 
     "It is a period of steady growth and stability before the challenges of adolescence."),
    ("How does physical growth in middle and late childhood compare to infancy and adolescence?", 
     "Growth is steady and predictable, with fewer rapid spurts."),
    ("What health characteristic defines middle and late childhood?", 
     "Children are healthier overall, with fewer life-threatening illnesses."),
    ("What physical changes emphasize stability in middle and late childhood?", 
     "Gradual changes allow time to refine skills and build confidence."),
    ("How do children in middle and late childhood become stronger and more coordinated?", 
     "Through improvements in both fine and gross motor skills, like in sports, handwriting, and art."),
    ("What allows children in middle and late childhood to take on more responsibility?", 
     "Cognitive and emotional growth, leading to increasing independence."),
    ("How do parents grant more freedom in middle and late childhood?", 
     "By allowing activities like walking to school, managing homework, and making simple choices."),
    ("How do peer relationships change in middle and late childhood?", 
     "They become more significant, sometimes outweighing parental influence."),
    ("What is the central developmental context in middle and late childhood?", 
     "Formal schooling."),
    ("How does school success or struggle affect children in middle and late childhood?", 
     "It strongly shapes self-esteem and future motivation."),
    ("What becomes a major socializing agent alongside family and peers in middle and late childhood?", 
     "Teachers and schools."),
    ("What increases during middle and late childhood regarding awareness of others?", 
     "Social comparison with peers."),
    ("What is the average annual height growth in middle and late childhood?", 
     "2–3 inches per year."),
    ("What is the average annual weight gain in middle and late childhood?", 
     "5–7 pounds per year."),
    ("What proportional changes occur in children's bodies during middle and late childhood?", 
     "Bodies become slimmer, muscle mass increases, and coordination improves."),
    ("Why are middle and late childhood considered the healthiest years?", 
     "Due to steady growth and low incidence of serious illnesses."),
    ("What brain area matures in middle and late childhood to boost attention and self-control?", 
     "Prefrontal cortex."),
    ("What process speeds up neural transmission in middle and late childhood?", 
     "Myelination."),
    ("What brain process removes unused connections in middle and late childhood?", 
     "Synaptic pruning, strengthening important pathways."),
    ("What improvements occur in gross motor skills during middle and late childhood?", 
     "Greater speed, strength, and endurance, like in running, jumping, and team sports."),
    ("What improvements occur in fine motor skills during middle and late childhood?", 
     "Better hand-eye coordination, like in writing, playing instruments, drawing, and crafts."),
    ("How does participation in organized sports and arts benefit children in middle and late childhood?", 
     "Fosters confidence and social skills."),
    ("What influences individual differences in motor development during middle and late childhood?", 
     "Gender, heredity, environment, socioeconomic status, nutrition, and opportunities."),
    ("What gender differences exist in motor skills during middle and late childhood?", 
     "Boys may excel slightly in gross motor strength; girls often show more fine motor coordination."),
    ("How do environmental opportunities shape motor skill development?", 
     "Access to sports, play spaces, and extracurriculars enhances skills."),
    ("Why is a balanced diet essential in middle and late childhood?", 
     "For energy, learning, and concentration in school."),
    ("How does malnutrition affect children in middle and late childhood?", 
     "Limits attention span and memory."),
    ("How does overnutrition affect children in middle and late childhood?", 
     "Harms physical and mental health, linked to obesity."),
    ("What risks are associated with childhood obesity?", 
     "Diabetes, heart disease, bullying, low self-esteem, and depression."),
    ("What is the most common chronic condition in childhood?", 
     "Asthma, influenced by genetics, environment, and air quality."),
    ("What chronic illnesses are increasing concerns in childhood?", 
     "Diabetes (Type 1 and Type 2), especially with obesity trends."),
    ("How do chronic illnesses affect school in middle and late childhood?", 
     "They impact attendance and participation."),
    ("What is the leading cause of death in middle and late childhood?", 
     "Accidents, such as motor vehicle crashes, bicycle accidents, falls, and drowning."),
    ("How can risks of accidents be reduced in middle and late childhood?", 
     "Through parental monitoring, helmets, seatbelts, and safe environments."),
    ("What public health measures reduce safety risks?", 
     "School safety programs, community awareness, and safer play spaces."),
    ("What Piaget stage occurs from 7–11 years?", 
     "Concrete operational stage."),
    ("In the concrete operational stage, what is conservation?", 
     "Understanding that quantity remains the same despite changes in shape."),
    ("In the concrete operational stage, what is classification?", 
     "Grouping objects into categories or hierarchies."),
    ("In the concrete operational stage, what is seriation?", 
     "Ordering items along a dimension, like length."),
    ("In the concrete operational stage, what is transitivity?", 
     "Understanding logical relationships, like if A > B and B > C, then A > C."),
    ("What declines in the concrete operational stage?", 
     "Egocentrism, allowing better consideration of others’ perspectives."),
    ("What does Vygotsky’s sociocultural approach emphasize?", 
     "Social interaction and culture in shaping thinking."),
    ("What is the Zone of Proximal Development (ZPD)?", 
     "The gap between what a child can do independently and with help."),
    ("What is scaffolding in Vygotsky’s theory?", 
     "Temporary support from teachers or peers, gradually removed as competence increases."),
    ("How is language used in Vygotsky’s theory?", 
     "As a tool for thought and self-regulation."),
    ("What improvements in attention occur in information processing during middle childhood?", 
     "Selective attention (focusing on relevant info) and sustained attention (staying focused over time)."),
    ("What memory strategies develop in middle childhood?", 
     "Rehearsal (repeating), organization (categorizing), elaboration (creating connections)."),
    ("What is metacognition in information processing?", 
     "Awareness and control of one’s own thinking; children monitor their learning."),
    ("What is executive function in information processing?", 
     "Higher-level processes like self-regulation, cognitive flexibility, and goal-setting."),
    ("What is Spearman’s theory of intelligence?", 
     "One general factor (g) influences all abilities."),
    ("What is Sternberg’s Triarchic Theory?", 
     "Three forms: analytical, creative, practical."),
    ("What is Gardner’s Multiple Intelligences theory?", 
     "Eight domains, e.g., linguistic, logical-mathematical, musical, bodily-kinesthetic, spatial, interpersonal, intrapersonal, naturalist."),
    ("How is intelligence typically measured?", 
     "Standardized IQ tests, with average = 100."),
    ("What are concerns about IQ tests?", 
     "Cultural bias; some favor certain backgrounds."),
    ("What is a push in intelligence assessment?", 
     "For fairer, culturally sensitive assessments."),
    ("What is dyslexia?", 
     "Difficulties with reading and spelling."),
    ("What is ADHD?", 
     "Inattention, hyperactivity, impulsivity affecting school performance."),
    ("What is emphasized for special learning needs?", 
     "Early identification and support."),
    ("How is giftedness defined?", 
     "IQ above 130 and/or exceptional ability in creativity, problem-solving, or motivation."),
    ("What do gifted programs aim to do?", 
     "Challenge and engage advanced learners."),
    ("What do inclusive education practices aim for?", 
     "Support diverse learners in general classrooms."),
    ("What strategies are used in inclusive education?", 
     "Differentiation, individualized education plans (IEPs), and fostering equity."),

    # Chapter 8
    ("How does self-understanding develop in children ages 8–11?", 
     "Shifts from concrete descriptions (e.g., 'I have brown hair') to psychological traits (e.g., 'I’m nice')."),
    ("What social aspects are increasingly included in self-descriptions by ages 8–11?", 
     "Group memberships and relationships (e.g., 'I’m a Girl Scout,' 'I have two close friends')."),
    ("What becomes central to self-definition after age 7?", 
     "Social comparison with peers."),
    ("How does understanding others improve in middle and late childhood?", 
     "Perspective taking allows considering others’ thoughts and feelings."),
    ("What executive functions are required for perspective taking?", 
     "Cognitive inhibition (suppressing own perspective) and cognitive flexibility (multiple viewpoints)."),
    ("What are linked to poor perspective-taking skills?", 
     "Peer difficulties, aggression, and selfishness."),
    ("How do children become less gullible with age?", 
     "They grow more skeptical of others’ claims."),
    ("What is self-esteem?", 
     "Global evaluation of self (self-worth, self-image)."),
    ("What is self-concept?", 
     "Domain-specific evaluations (academic, athletic, appearance, etc.)."),
    ("What influences self-esteem and self-concept?", 
     "Early parent–child relationships, secure attachment, and parental support."),
    ("What does high self-esteem lead to?", 
     "Greater initiative, which can be prosocial or antisocial."),
    ("What is low self-esteem linked to?", 
     "Anxiety, depression, obesity, delinquency, and lower life satisfaction."),
    ("What is self-efficacy?", 
     "Belief in one’s ability to master tasks; linked to achievement."),
    ("What is self-regulation?", 
     "Managing emotions, behavior, and thoughts to achieve goals."),
    ("Why are self-efficacy and self-regulation essential?", 
     "For success in school and coping with challenges."),
    ("What is one strategy to improve self-esteem?", 
     "Identify causes of low self-esteem and help children value areas of competence."),
    ("What is another strategy to improve self-esteem?", 
     "Provide emotional support and social approval."),
    ("What is a third strategy to improve self-esteem?", 
     "Encourage achievement through real skill-building."),
    ("What is a fourth strategy to improve self-esteem?", 
     "Teach coping strategies to face problems constructively."),
    ("What is Erikson’s fourth stage?", 
     "Industry vs. Inferiority (ages 6–11)."),
    ("What does industry involve in Erikson’s stage?", 
     "Eagerness to learn, satisfaction from making, building, and completing tasks."),
    ("What fosters industry?", 
     "Success, leading to confidence, competence, and motivation."),
    ("What leads to inferiority in Erikson’s stage?", 
     "Efforts dismissed or criticized, causing inadequacy and lack of confidence."),
    ("What is the overall theme of industry vs. inferiority?", 
     "Balance between competence and doubt, shaped by encouragement from parents, teachers, and peers."),
    ("How does emotional understanding improve in middle and late childhood?", 
     "Children understand complex emotions like pride and shame, tied to responsibility."),
    ("What do children realize about emotions in middle childhood?", 
     "A situation can involve multiple emotions at once, like joy and anxiety."),
    ("What awareness develops regarding emotional causes?", 
     "Links between past events and current feelings."),
    ("How do children learn emotional control?", 
     "Suppress or adjust reactions, like hiding anger."),
    ("What self-initiated strategies develop for emotion regulation?", 
     "Reflection and cognitive techniques, like calming themselves."),
    ("What is genuine empathy?", 
     "Ability to feel concern and share in others’ emotional experiences."),
    ("What is the aim of social-emotional education programs?", 
     "Improve emotional, social, and academic outcomes."),
    ("What does the Second Step Program focus on for Pre-K?", 
     "Self-regulation and executive function."),
    ("What does the Second Step Program focus on for K–5?", 
     "Friendship, emotion regulation, problem-solving."),
    ("What does the Second Step Program focus on for grades 6–8?", 
     "Communication, coping with stress, decision making."),
    ("What are the five domains of the CASEL Framework?", 
     "Self-awareness, self-management, social awareness, relationship skills, responsible decision making."),
    ("How do older children cope with stress better?", 
     "Better at appraising stress, recognizing control, and generating alternatives."),
    ("What cognitive strategies do children use for stress?", 
     "Shifting thoughts, reframing stressful events."),
    ("By what age can most children use cognitive coping effectively?", 
     "Age 10."),
    ("What reduces children's ability to cope with stress?", 
     "Family turmoil or trauma."),
    ("What can disasters and trauma cause in children?", 
     "Acute stress, depression, PTSD; outcomes depend on severity and support."),
    ("What is the dose-response effect in trauma?", 
     "Greater exposure leads to worse adjustment."),
    ("How does support help children after trauma?", 
     "From parents/teachers, building resilience."),
    ("What is heteronomous morality in Piaget’s theory?", 
     "Rules are fixed, unchangeable, handed down by authority (younger children)."),
    ("What is autonomous morality in Piaget’s theory?", 
     "Rules created by people, changeable; intentions matter more than consequences (by ~10 years)."),
    ("What is punishment in autonomous morality?", 
     "Does not always follow wrongdoing."),
    ("What is Kohlberg’s preconventional reasoning level?", 
     "Morality based on external rewards and punishments; 'What’s in it for me?' (before age 9)."),
    ("What is Kohlberg’s conventional reasoning level?", 
     "Conformity to social rules and expectations (early adolescence)."),
    ("What is Kohlberg’s postconventional reasoning level?", 
     "Morality based on internal principles; recognizes alternatives (early adulthood, small minority)."),
    ("Is progression in Kohlberg’s theory universal?", 
     "Yes in sequence, but not all reach postconventional."),
    ("What influences moral development beyond cognitive growth?", 
     "Peer interactions for perspective taking, negotiation, and moral conflict."),
    ("What is a criticism of Kohlberg’s theory regarding thought vs. behavior?", 
     "Knowing right does not ensure doing right."),
    ("What is another criticism of Kohlberg’s theory?", 
     "Morality often intuitive ('gut reactions'), not just deliberate (Haidt)."),
    ("What does Kohlberg underemphasize according to critics?", 
     "Gender, culture, and family influences."),
    ("What is domain theory of moral development?", 
     "Children’s reasoning from experiences with moral, social conventional, and personal situations."),
    ("What are moral rules in domain theory?", 
     "Obligatory, universal, impersonal; concern lying, cheating, harming; violations more serious."),
    ("What are social conventional rules?", 
     "Created by consensus for order; arbitrary, changeable (e.g., raising hand in class)."),
    ("What is personal reasoning in domain theory?", 
     "Matters of discretion, like body control, privacy, choice of friends/activities."),
    ("What is prosocial behavior?", 
     "Helping, sharing, empathy; increases from preschool to adolescence."),
    ("How does sharing evolve with age?", 
     "Young: fairness as equality; older: equity based on merit/needs."),
    ("What is Gilligan’s critique of Kohlberg?", 
     "Theory may reflect gender bias."),
    ("What gender stereotypes persist in middle/late childhood?", 
     "E.g., 'math is for boys.'"),
    ("What gender differences exist in academic performance?", 
     "Girls outperform boys in reading, writing, engagement; boys slight advantage in visuospatial."),
    ("Overall, are there more gender similarities or differences?", 
     "More similarities."),
    ("In what type of aggression are boys more involved?", 
     "Physical aggression, stronger when provoked; influenced by biology and environment."),
    ("What are differences in verbal aggression by gender?", 
     "Small; sometimes girls show slightly more."),
    ("What is relational aggression?", 
     "Harming through social manipulation (rumors, exclusion); increases in middle/late childhood."),
    ("Which gender shows higher relational aggression?", 
     "Girls, especially in adolescence."),
    ("How do females differ in emotion expression?", 
     "Express more emotion, better at decoding, smile/cry more, report higher happiness."),
    ("How do males differ in emotion expression?", 
     "Report/express more anger, less self-regulation, linked to behavioral problems."),
    ("How do females differ in prosocial behavior?", 
     "More prosocial, empathetic, kind; slightly more likely to share."),
    ("How do males differ in prosocial behavior?", 
     "Engage less overall."),
    ("How do gender roles vary across cultures?", 
     "Strongly divided in some Middle Eastern/Asian countries (men providers, women caretakers)."),
    ("In global studies, who holds more egalitarian gender attitudes?", 
     "Girls, especially in countries with higher gender equality."),
    ("How do parent-child relationships change in middle/late childhood?", 
     "Less time together, but parents remain guides, managers, supervisors; shift to coregulation."),
    ("Which parent is often more active as manager?", 
     "Mothers; linked to better grades and fewer school problems."),
    ("What is secure attachment linked to in middle childhood?", 
     "Lower anxiety, depression, better autonomy support."),
    ("What are common stepfamily structures?", 
     "Stepfather, stepmother, blended."),
    ("How do children in stepfamilies compare to intact families?", 
     "More adjustment problems, but most without serious issues."),
    ("How does adjustment in stepfamilies change over time?", 
     "Improves, especially in simple stepfamilies."),
    ("What reduces conflict in stepfamilies?", 
     "Positive stepparent–child relationships."),
    ("How does peer interaction change with age?", 
     "Increases from ~10% at age 2 to ~30% by middle/late childhood."),
    ("By elementary school, how many daily peer exchanges occur?", 
     "~300 (classic study)."),
    ("How do peer groups change in middle childhood?", 
     "Expand, become less adult-supervised."),
    ("Until what age does same-sex peer preference continue?", 
     "~Age 12."),
    ("What is sociometric status?", 
     "Degree liked/disliked by peers, measured by nominations."),
    ("What is popular sociometric status?", 
     "Frequently chosen as best friend; rarely disliked."),
    ("What is average sociometric status?", 
     "Average positive/negative nominations."),
    ("What is neglected sociometric status?", 
     "Rarely chosen as best friend; not disliked."),
    ("What is rejected sociometric status?", 
     "Rarely chosen; actively disliked."),
    ("What is controversial sociometric status?", 
     "Both highly liked and disliked."),
    ("What characteristics do popular children have?", 
     "Strong social skills, happy, emotionally controlled, enthusiastic, caring, self-confident."),
    ("What risks do rejected children face?", 
     "Higher adjustment problems, depression, conduct issues, delinquency, self-injury."),
    ("What is social cognition in peer relations?", 
     "Thinking about social matters, like interpreting intent and peer behavior."),
    ("What is Dodge’s first step in social information processing?", 
     "Attend to social cues."),
    ("What is Dodge’s second step?", 
     "Attribute intent."),
    ("What is Dodge’s third step?", 
     "Generate goals."),
    ("What is Dodge’s fourth step?", 
     "Access behavioral scripts from memory."),
    ("What is Dodge’s fifth step?", 
     "Make decisions."),
    ("What is Dodge’s sixth step?", 
     "Enact behavior."),
    ("How do aggressive boys process social information?", 
     "Interpret ambiguous intent as hostile; respond quickly without reflection."),
    ("What social knowledge must children have?", 
     "Goals in unclear situations, how to initiate/maintain friendships, social scripts."),
    ("What is bullying?", 
     "Verbal/physical behavior to disturb a less powerful person."),
    ("What is the prevalence of bullying in U.S. grades 6–10?", 
     "Nearly one-third involved as victim or perpetrator."),
    ("What gender differences exist in bullying?", 
     "Boys more likely bullies; boys physically bullied; girls face-to-face/cyberbullied."),
    ("What are characteristics of bullying victims?", 
     "Anxious, withdrawn, or aggressive; less likely to retaliate."),
    ("In what social context does bullying often occur?", 
     "70–80% in same classroom; bullies seek audience/status; many not rejected."),
    ("What are short-term effects of bullying?", 
     "Loneliness, difficulty making friends, low grades, risky behaviors."),
    ("What mental health risks come from bullying?", 
     "Depression, suicidal ideation, attempts."),
    ("What physical/behavioral risks come from bullying?", 
     "Weight gain, disordered eating, sleep problems."),
    ("What are long-term effects of bullying?", 
     "Difficulty forming relationships, workplace challenges, increased mental health service use."),
    ("On what is children's friendship typically based?", 
     "Similarity in age, sex, race, attitudes, achievement goals."),
    ("What do friends share regarding education?", 
     "Educational aspirations and school orientations."),
    ("What is companionship in friendship functions?", 
     "Someone to spend time and engage in activities with."),
    ("What is stimulation in friendship functions?", 
     "Excitement, amusement, new information."),
    ("What is physical support in friendship functions?", 
     "Resources, assistance, time."),
    ("What is ego support in friendship functions?", 
     "Encouragement and feedback building self-esteem."),
    ("What is social comparison in friendship functions?", 
     "Information about how one measures up."),
    ("What is affection and intimacy in friendship functions?", 
     "Warm, close, trusting relationship; self-disclosure (appears in early adolescence)."),
    ("What is linked to positive friendships?", 
     "Self-esteem, well-being, academic success."),
    ("What can negative friendships lead to?", 
     "Harmful development if coercive or conflict-ridden."),
    ("How do students with academically oriented friends perform?", 
     "More likely to succeed academically."),
    ("What does school shape as a social context?", 
     "Self-concept, provides new evaluation standards."),
    ("In 2015 TIMSS, where did U.S. 4th graders rank in math?", 
     "11th out of 48."),
    ("In 2015 TIMSS, where did U.S. 4th graders rank in science?", 
     "8th out of 48."),
    ("In 2015 TIMSS, where did U.S. 8th graders rank in math and science?", 
     "8th out of 37."),
    ("What trend occurs in U.S. students’ international rankings?", 
     "Decline from elementary to high school."),
    ("What countries are top performers in achievement?", 
     "East Asian (Singapore, China, Japan), Finland, Estonia."),
    ("In Stevenson’s research, how do Asian students compare to Americans?", 
     "Outperform, with gap widening over time."),
    ("What key difference in instructional time for math?", 
     "Japan 25% of time; U.S. 10%."),
    ("What is the school year length difference?", 
     "Asian ~240 days; U.S. ~178 days."),
    ("What do Asian parents expect?", 
     "Higher achievement."),
    ("What belief do U.S. parents hold about success?", 
     "Due to innate ability."),
    ("What belief do Asian parents hold about success?", 
     "Due to effort and training."),
    ("What difference in homework?", 
     "Asian students do more; parents provide more help."),
    ("What is East Asian parenting often like?", 
     "High involvement, authoritarian or controlling (e.g., 'Tiger Mother')."),
    ("What pros of East Asian parenting?", 
     "Higher achievement."),
    ("What cons of East Asian parenting?", 
     "Higher depression, anxiety, aggression, poorer social skills."),
    ("What parenting style is linked to better adjustment in China?", 
     "Authoritative over authoritarian."),
    ("What is a fixed mindset?", 
     "Qualities are unchangeable."),
    ("What is a growth mindset?", 
     "Qualities can improve with effort."),
    ("How are mindsets shaped?", 
     "By parents/teachers early on."),
    ("What strategy promotes growth mindset?", 
     "Teach for understanding."),
    ("What is another strategy for growth mindset?", 
     "Provide feedback for improvement."),
    ("What is a third strategy for growth mindset?", 
     "Allow revision of work."),
    ("What is a fourth strategy for growth mindset?", 
     "Emphasize effort and struggle in learning."),

    # Chapter 9
    ("What historical view did G. Stanley Hall have of adolescence (1904)?", 
     "'Storm-and-stress' with conflict and mood swings."),
    ("What did Daniel Offer find in 1988 about adolescents?", 
     "73% have a healthy self-image."),
    ("What conclusion about adolescence stereotypes?", 
     "Not purely negative; stereotypes exaggerated."),
    ("What do adolescents explore?", 
     "New identities, styles, behaviors."),
    ("What is boundary testing in adolescence?", 
     "Normal, healthy step toward adult values."),
    ("What fuels negative stereotypes of adolescents?", 
     "Media focus on minority of troubled youth."),
    ("What is the norm in adolescent development?", 
     "Positive development."),
    ("What is adolescence a time of?", 
     "Evaluation, decision-making, identity formation, not just rebellion."),
    ("Where do adolescent problems often come from?", 
     "Lack of opportunities and adult support, not adolescents themselves."),
    ("What is a strength-based approach (Benson)?", 
     "Focus on wellness, skills, competencies over eliminating risks."),
    ("What is puberty?", 
     "Brain-neuroendocrine process in early adolescence; growth, sexual maturation, hormonal changes."),
    ("What is the typical order of sexual maturation for boys?", 
     "1. Testes/penis growth, 2. Pubic hair, 3. Minor voice change, 4. First ejaculation, 5. Growth spurt, 6. Armpit hair, 7. Deeper voice, 8. Facial hair."),
    ("What is the typical order of sexual maturation for girls?", 
     "1. Breast development or pubic hair, 2. Armpit hair, 3. Growth spurt, 4. Hips widen, 5. Menarche."),
    ("When do girls' growth spurts start and peak?", 
     "Start ~9, peak ~11.5 years."),
    ("When do boys' growth spurts start and peak?", 
     "Start ~11, peak ~13.5 years."),
    ("What gland regulates eating and sex?", 
     "Hypothalamus."),
    ("What gland regulates growth and other glands?", 
     "Pituitary gland."),
    ("What are the gonads?", 
     "Testes and ovaries."),
    ("What does testosterone influence?", 
     "Male genital growth, height, voice."),
    ("What does estradiol (estrogen) influence?", 
     "Female breast, uterine, skeletal development."),
    ("Do hormones alone explain adolescent mood and behavior?", 
     "No; social factors explain more."),
    ("What trend in puberty timing worldwide?", 
     "Onset earlier, linked to nutrition, health, BMI, stress."),
    ("When does puberty start and end for boys?", 
     "Start ~10–13.5, end ~13–17."),
    ("When is menarche for girls?", 
     "~9–15 years."),
    ("What accelerates puberty?", 
     "Stress/conflict, e.g., abuse."),
    ("What are adolescents highly focused on?", 
     "Appearance and body image."),
    ("What is linked to positive body image?", 
     "Healthy behaviors like exercise."),
    ("How does social media impact body image?", 
     "More use = higher dissatisfaction; girls more affected."),
    ("For boys, what are effects of early maturation?", 
     "Positive self-perceptions, better peer relations in adolescence."),
    ("For boys, what are effects of late maturation?", 
     "Stronger identity in adulthood."),
    ("For girls, what risks come from early maturation?", 
     "Depression, antisocial behavior, smoking/drinking, eating disorders, earlier dating/sex, delinquency, lower graduation."),
    ("Why are early-maturing girls at risk?", 
     "Social/cognitive immaturity + adultlike bodies expose to problem contexts."),
    ("What continues in the adolescent brain?", 
     "Neuroplasticity; development from basic drives to higher control."),
    ("What is synaptic pruning in adolescence?", 
     "Unused connections pruned; used strengthened for efficiency."),
    ("What thickens in the adolescent brain?", 
     "Corpus callosum for better processing."),
    ("What matures late in the adolescent brain (18–25+)?", 
     "Prefrontal cortex (reasoning, planning, self-control)."),
    ("What matures earlier than PFC?", 
     "Limbic system (emotions/reward), leading to strong emotions with immature control."),
    ("What rises in PFC and limbic areas?", 
     "Dopamine, increasing reward seeking, risk-taking, drug vulnerability."),
    ("What improves with age in the brain?", 
     "Efficient local activation + stronger long-range networks (e.g., PFC–hippocampus)."),
    ("What is linked to reduced PFC–amygdala connectivity?", 
     "Higher depression risk."),
    ("Do nature and nurture shape the adolescent brain?", 
     "Yes; experiences like parenting and poverty interventions matter."),
    ("What caution about adolescent brain evidence?", 
     "Much is correlational, not causal."),
    ("What is sexual identity?", 
     "Activities, interests, styles, orientation."),
    ("What variability exists in adolescents' sexual development?", 
     "In anxiety, arousal, activity level, religious influence."),
    ("What paths do sexual minority youth take?", 
     "Diverse; some abrupt realization, many bisexual attractions; most develop competently but higher health risks."),
    ("By grade 12, what percentage have had intercourse?", 
     "Majority."),
    ("By age 20, what percentage have had intercourse?", 
     "~3/4."),
    ("From 1991–2017, what trends in U.S. adolescent sexual activity?", 
     "Declines in ever had sex, currently active, <13 first, 4+ partners."),
    ("What ethnic patterns in sexual initiation?", 
     "Earlier among African American; later among Asian American."),
    ("What is linked to early sexual debut (≤15)?", 
     "Lower graduation, more partners, no condom, pregnancy, substance use, antisocial behavior."),
    ("What increases chance of very early intercourse?", 
     "Substance abuse, mental health problems."),
    ("What family influence delays sexual initiation?", 
     "High-quality time with parents, knowledge/rules, supportive parenting."),
    ("What does protection-focused extended-family talk lead to?", 
     "Fewer partners."),
    ("What does risk-focused extended-family talk lead to?", 
     "More partners."),
    ("What risks does sexual activity bring?", 
     "Unintended pregnancy, STIs."),
    ("What reduces pregnancy and STI risks?", 
     "Condoms, but many use inconsistently."),
    ("In 2018, what % of U.S. high school students used contraceptives at last intercourse?", 
     "53.8% (up from 46% in 1991)."),
    ("How do U.S. teens compare to Europeans in condom use?", 
     "Less likely."),
    ("What is LARC?", 
     "Long-Acting Reversible Contraception (IUDs, implants); more effective than pills/condoms."),
    ("What organizations recommend LARC?", 
     "AAP, ACOG, WHO."),
    ("What was LARC use in U.S. 2013–2017?", 
     "Rose from 1.8% to 5.3%."),
    ("What are STIs?", 
     "Infections transmitted through sexual contact (oral-genital, anal-genital)."),
    ("In 2017 U.S., how many new STI infections?", 
     "~20 million; half in 15–24-year-olds."),
    ("What % of new HIV cases in ages 13–24?", 
     "21%; 81% gay/bisexual males."),
    ("What are common STIs?", 
     "Chlamydia, HPV."),
    ("Do birth control pills prevent STIs?", 
     "No, only pregnancy."),
    ("How does U.S. adolescent pregnancy rate compare to developed nations?", 
     "One of highest; 8x Netherlands."),
    ("What trend in U.S. adolescent births 1991–2017?", 
     "Declined from 61.8 to 18.8 per 1,000 (ages 15–19)."),
    ("What 2017 ethnic differences in births per 1,000 (15–19)?", 
     "Latinas 28.9, African Americans 27.5, Non-Latina Whites 13.2, Asian Americans 3.3."),
    ("What trend in teen repeat births 2004–2015?", 
     "Declined from 21% to 17%."),
    ("What lowers repeat pregnancy risk?", 
     "Effective contraception (LARC), continued schooling."),
    ("What increases repeat pregnancy risk?", 
     "Depression, abortion history."),
    ("What health risks for babies of adolescent mothers?", 
     "Low birth weight, infant mortality, neurological/childhood illness."),
    ("What risks for adolescent mothers?", 
     "Dropout, depression, substance use, poverty, unemployment, welfare reliance, lower education."),
    ("What cycle occurs with adolescent pregnancy?", 
     "Daughters at increased risk for teen pregnancy."),
    ("What reduces teen pregnancy rates?", 
     "Family education, programs like Girls Inc."),
    ("Why is adolescence a critical juncture for health?", 
     "Key stage for health behavior formation."),
    ("What do negative behaviors in adolescence link to?", 
     "Early death in adulthood."),
    ("What do positive behaviors in adolescence provide?", 
     "Immediate benefits, long-term protection against diseases."),
    ("What eating issues are common in adolescents?", 
     "Overweight/obesity, eating disorders."),
    ("What trend in overweight U.S. adolescents (12–19) early 1990s–2016?", 
     "Rose from 11% to 20.6%."),
    ("What does obesity in adolescence predict?", 
     "Later severe obesity in emerging adulthood."),
    ("What trend in overweight from age 14–24?", 
     "Increased from 20% to 33%."),
    ("What trend in physical activity through adolescence?", 
     "Declines."),
    ("What % of adolescents get ≥60 min vigorous activity daily?", 
     "Girls ~36.8%, boys ~56.9%."),
    ("Which group is most active?", 
     "Non-Latino White boys."),
    ("Which group is least active?", 
     "African American girls."),
    ("What physical benefits of exercise in adolescence?", 
     "Lower obesity, improved weight, triglycerides, BP; lower type 2 diabetes; better sleep."),
    ("What interventions improve health in adolescents?", 
     "After-school athletics, jump rope programs for obese girls."),
    ("What mental/cognitive benefits of exercise?", 
     "Lower depressive symptoms, fewer emotional/peer problems; improved memory."),
    ("How do family meals relate to health?", 
     "Linked to healthier weight."),
    ("How do peers influence activity?", 
     "Peers’ activity predicts one’s; girls influenced by both genders, boys by females."),
    ("How does screen time affect health?", 
     "More time = less exercise, higher overweight/obesity."),
    ("What is linked to short sleep (<7h)?", 
     "Overweight, depression/anxiety, low motivation, self-harm/suicidal thoughts."),
    ("What are dose effects of short sleep?", 
     "<7.7h average = more emotional/peer problems, anxiety, suicidal ideation."),
    ("What compounds risk with short sleep?", 
     "Low activity; worse in lower-SES; tied to alcohol/marijuana."),
    ("What % get ≥8h sleep on school nights?", 
     "Only ~25%; declines with age."),
    ("Why the biological sleep shift in adolescence?", 
     "Melatonin released ~1h later; need ~9h25m."),
    ("What benefits from later school starts?", 
     "More sleep (+34 min), higher GPA (+4.5%), better attendance, fewer discipline/illness/depression."),
    ("What disrupts sleep?", 
     "Phones/tablets, caffeine."),
    ("In emerging adulthood, what about sleep?", 
     "Many poor-quality; short sleep = worse attention; interventions help (device cutoff, schedules)."),
    ("What are top causes of death ages 15–24?", 
     "Unintentional injuries (~½, esp. motor vehicle), suicide (#2), homicide (#3)."),
    ("What contributes to risky driving?", 
     "Speeding, tailgating, DUI; ~50% teen MV fatalities BAC ~0.10%."),
    ("What predicts later DWI/blackouts?", 
     "Binge drinking in 12th grade."),
    ("What trends in substance use since 1990s?", 
     "Declines in LSD, cocaine, cigarettes, sedatives, tranquilizers, MDMA."),
    ("What is the most widely used illicit drug?", 
     "Marijuana; legalization may increase youth use."),
    ("What about vaping trends?", 
     "Nicotine vaping > smoking; e-cigs gateway to cigarettes/marijuana."),
    ("What predicts heavy adult drinking?", 
     "Early onset (≤11–early teens)."),
    ("What protective factors against substance use?", 
     "Parental monitoring, family dinners, educational success."),
    ("What influences substance use?", 
     "Friends’ use strongly predicts own; friends’ alcohol > parents’."),
    ("What is anorexia nervosa?", 
     "Pursuit of thinness via starvation; low weight, fear of gain, distorted image."),
    ("What is anorexia profile?", 
     "Onset early–mid adolescence; 10x females; perfectionistic; non-Latina White, higher-SES."),
    ("What influences anorexia?", 
     "Genetic, family, cultural/media (thin-ideal, social media)."),
    ("What treatment for anorexia?", 
     "Family therapy for teens; cognitive approaches."),
    ("What is bulimia nervosa?", 
     "Binge–purge cycles; large amount in ≤2h + loss of control."),
    ("What is bulimia profile?", 
     "Late adolescence/early adulthood; 1–2% women; 90% female; normal weight; depression/anxiety."),
    ("What treatment for bulimia?", 
     "CBT effective; family/cognitive therapies."),
    ("What comorbidity with eating disorders?", 
     "Higher major depressive disorder, alcohol use disorder."),
    ("What is Piaget’s concrete operational stage (≈7–11)?", 
     "Logical reasoning about concrete events; classification, relations."),
    ("What is Piaget’s formal operational stage (≈11+)?", 
     "Abstract, idealistic, logical thinking; hypotheticals."),
    ("What is hypothetical-deductive reasoning?", 
     "Generate hypotheses, deduce implications, test systematically."),
    ("What do early formal operations show?", 
     "Idealism and 'what-could-be' thinking."),
    ("What evaluation of Piaget’s stages?", 
     "Variation; only ~1/3 young adolescents show formal ops; many adults don’t."),
    ("What matters more than Piaget proposed?", 
     "Education, culture; training promotes formal ops."),
    ("Is development stage-like?", 
     "Less so; abilities appear earlier/later than thought."),
    ("What are Piaget’s lasting contributions?", 
     "Children as active thinkers; concepts like assimilation, accommodation, conservation, egocentrism."),
    ("What is adolescent egocentrism (Elkind)?", 
     "Heightened self-consciousness."),
    ("What is imaginary audience?", 
     "Belief others watch/care as much; 'on stage' behavior."),
    ("What is personal fable?", 
     "Uniqueness (no one understands) and invincibility (risk underestimation)."),
    ("What else may teens sense?", 
     "Vulnerability to early death."),
    ("What about information processing in adolescence?", 
     "Wide individual differences; adolescents produce own cognitive development."),
    ("What is executive function (EF)?", 
     "Higher-order processes for goal-directed behavior, self-control (linked to PFC)."),
    ("What is cool EF?", 
     "Deliberate, logical control; increases with age."),
    ("What is hot EF?", 
     "Emotion-driven; peaks ~14–15, then declines."),
    ("What is cognitive control?", 
     "Sustain attention, inhibit interference, shift flexibly; improves into emerging adulthood."),
    ("What distractions affect cognitive control?", 
     "External (peers, devices), internal (worry)."),
    ("What can reduce test anxiety?", 
     "Attention training interventions."),
    ("How does decision making improve with age?", 
     "Better options, perspectives, consequences, source evaluation."),
    ("What is gist-based evaluation?", 
     "Quickly recognize danger and cue values."),
    ("How does emotion affect decisions?", 
     "Calm = wiser; arousal = riskier."),
    ("How does social context affect decisions?", 
     "Temptations and peers increase risk-taking, immediate rewards."),
    ("How to improve adolescent decisions?", 
     "Role-plays, peer problem solving, realistic scenarios."),
    ("What happens in transition to middle/junior high?", 
     "Dips in satisfaction/commitment; teacher warmth drops, lower math scores."),
    ("What changes coincide with middle school transition?", 
     "Puberty, formal operations, responsibility, larger schools, multiple teachers, achievement pressure."),
    ("What is the top-dog phenomenon?", 
     "From oldest in elementary to youngest in middle school; lower self-concept."),
    ("What positives of middle school transition?", 
     "Feel grown up, more courses, intellectual challenge, peer time, independence."),
    ("What problems in middle schools (Carnegie Council)?", 
     "Impersonal, irrelevant curricula, low health/counseling access."),
    ("What recommendations for effective middle schools?", 
     "Smaller houses, lower student-counselor ratios, parent involvement, integrated curricula, team-teaching, health/fitness."),
    ("What concerns in high schools?", 
     "~25% grads college-ready; low expectations, passive learning."),
    ("How do high school transitions affect relationships?", 
     "Worsen teacher–student; motivation drops, conflict rises."),
    ("How can peer culture affect academics?", 
     "Stigma for not fitting in derails academics."),
    ("What trend in dropout rates to 2016?", 
     "Declined to ~6% (ages 16–24)."),
    ("What variations in dropout rates?", 
     "By ethnicity, gender, location; high in inner-city."),
    ("What reasons for dropout?", 
     "School dislike/discipline, economic pressures, pregnancy/marriage."),
    ("What prevents dropout?", 
     "Early reading, tutoring, counseling, mentoring, school engagement."),
    ("What is service learning?", 
     "Education promoting social responsibility and community service."),
    ("What activities in service learning?", 
     "Tutoring, assisting elders, hospital volunteering, child-care, clean-ups."),
    ("What core goals of service learning?", 
     "Reduce self-centeredness, increase motivation to help, develop empathy/civic engagement."),
    ("When does service learning work best?", 
     "Student choice in activity; structured reflection (journals, discussions)."),
    ("Who benefits from service learning?", 
     "Adolescents (skills, insight, academic/psychosocial); recipients/communities."),
    ("What outcomes for adolescents in service learning?", 
     "Higher grades, goal setting, self-esteem, sense of difference, future volunteering."),
    ("What participation difference in service learning?", 
     "Girls > boys."),

    # Chapter 10
    ("What is the centrality of identity in adolescence?", 
     "Universal concern; choices shape career, relationships, values, lifestyle."),
    ("What is identity not?", 
     "Not a single construct; self-portrait of multiple domains."),
    ("What domains compose identity?", 
     "Career/vocational, political/religious, relationship/sexual, cultural/ethnic, personality, interests, body image."),
    ("How does identity develop?", 
     "Gradually, through affirmation, negotiation, reevaluation."),
    ("What is Erikson’s Stage 5?", 
     "Identity vs. Identity Confusion (adolescence)."),
    ("What challenge do adolescents face in Erikson’s stage?", 
     "Defining who they are and where going."),
    ("What is psychosocial moratorium?", 
     "Period between childhood security and adult autonomy for exploration."),
    ("What do adolescents experiment with in moratorium?", 
     "Roles like career, appearance, activities."),
    ("What are Marcia’s identity statuses based on?", 
     "Exploration and commitment."),
    ("What is identity diffusion?", 
     "No exploration, no commitment; little interest in roles."),
    ("What is identity foreclosure?", 
     "Commitment without exploration; often from parents/authority."),
    ("What is identity moratorium?", 
     "Active exploration, no commitment; in crisis."),
    ("What is identity achievement?", 
     "Exploration followed by commitment; stable self."),
    ("What are key processes in Marcia?", 
     "Exploration (crisis) – searching alternatives; commitment – personal investment."),
    ("What is the dual-cycle model?", 
     "Formation: exploration in breadth + identification; maintenance: exploration in depth + reconsideration."),
    ("What is narrative identity?", 
     "Constructing life stories to integrate experiences."),
    ("What stories focus on in narrative identity?", 
     "Interpersonal relationships, family, friendships."),
    ("When does identity formation begin?", 
     "Infancy (attachment, independence); continues lifespan."),
    ("When do key identity changes occur?", 
     "Late adolescence/emerging adulthood (18–25); cognitive maturity + social experiences integrate domains."),
    ("What is college's role in identity?", 
     "Laboratory for exploration: diverse peers, courses, perspectives."),
    ("How dynamic is identity?", 
     "Remains dynamic; MAMA cycles (moratorium-achievement) repeat."),
    ("What influences identity development?", 
     "Parents (secure attachment = achievement); peers (diverse friendships); digital (social media curation)."),
    ("What is ethnic identity?", 
     "Sense of membership in ethnic group, with attitudes/feelings."),
    ("What identity do most minority adolescents form?", 
     "Bicultural: balancing ethnic and majority culture."),
    ("When are turning points for ethnic identity?", 
     "Adolescence/emerging adulthood for reflecting on ethnicity."),
    ("What is positive ethnic identity associated with?", 
     "High self-esteem, motivation, coping with discrimination, achievement, resilience."),
    ("What generational patterns in ethnic identity?", 
     "First-gen: strong heritage ties; second-gen: stronger American, ethnic retention via language/networks; later: influenced by social/political contexts."),
    ("What reshapes family relationships in adolescence?", 
     "Renegotiation of roles."),
    ("What are three core themes in adolescent family dynamics?", 
     "Parental management/monitoring, autonomy/attachment, parent-adolescent conflict."),
    ("What is parental monitoring?", 
     "Supervision of settings, activities, friendships, academics."),
    ("What is monitoring linked to?", 
     "Higher grades, delayed sex, more condom use, reduced marijuana/cigarettes, better sleep."),
    ("What predicts healthier behaviors?", 
     "Active tracking in adolescence/college."),
    ("What about disclosure vs. secrecy?", 
     "Adolescents manage info; disclosure with trust/acceptance; secrecy linked to problems."),
    ("What is the push for autonomy?", 
     "Seek independence/responsibility; clashes with parents."),
    ("How should parents guide autonomy?", 
     "Relinquish control where reasonable; guide where experience limited."),
    ("How does autonomy develop?", 
     "Gradually through negotiation."),
    ("What cultural/gender differences in autonomy?", 
     "Boys more than girls; Latino more protective of daughters; Mexican-origin girls seek earlier."),
    ("Why does secure attachment matter in adolescence?", 
     "Better peer relations, emotional regulation; fewer difficulties, delinquency, substance use, depression."),
    ("What is insecure attachment associated with?", 
     "Delinquency, maltreatment, higher addiction."),
    ("When does parent-adolescent conflict increase?", 
     "Early adolescence, peaks mid, declines."),
    ("What are usual conflict topics?", 
     "Mundane issues like chores, curfews, clothing, technology."),
    ("What improves relationships after high school?", 
     "Going to college vs. staying home."),
    ("What positive role does minor conflict serve?", 
     "Helps transition to autonomy, practice decision-making/boundaries."),
    ("What is linked to intense/prolonged conflict?", 
     "Running away, delinquency, dropout, early pregnancy/marriage, substance abuse, cult involvement."),
    ("What about immigrant families?", 
     "Adolescents acculturate faster; gap heightens conflict."),
    ("In Chinese American families, what is conflict linked to?", 
     "Alienation, depression, delinquency, lower achievement."),
    ("What is the old model of parent-adolescent relationships?", 
     "Detach for autonomy; intense, stressful conflict."),
    ("What is the new model of parent-adolescent relationships?", 
     "Parents remain attachments/supports; moderate conflict serves purpose; disputes foster independence."),
    ("Why do peers matter in adolescence?", 
     "Reshape experience, social learning, romantic competence."),
    ("What predicts romantic satisfaction in late 20s?", 
     "Early peer assertiveness (15–16), close-friendship capacity (16–18)."),
    ("What developmental shift in friendships?", 
     "From broad popularity (childhood) to fewer, intense/intimate (adolescence)."),
    ("What rises in adolescence with friends?", 
     "Self-disclosure; dips with parents, rebounds in college."),
    ("What are Sullivan’s social needs in adolescence?", 
     "Tenderness/security, companionship, acceptance, intimacy, sexual relations."),
    ("When does intimacy intensify?", 
     "Early adolescence; close friendships central."),
    ("What happens if close friends not secured?", 
     "Loneliness, lowered self-worth."),
    ("What predicts positive romantic relationships at 20–23?", 
     "Secure friendships at 16."),
    ("What risks from poor-quality friendships?", 
     "Coercive/conflict; friends’ delinquency/substance/dieting/ED/depression/self-harm contagion."),
    ("What protections from good friendships?", 
     "Skilled/supportive/academic friends = lower delinquency/substance/risky sex/bullying; higher achievement."),
    ("What ethnic patterns in achievement and friendships?", 
     "White/Asian: same-ethnic; African American/Latino: cross-ethnic."),
    ("What about mixed-age friendships?", 
     "Older peers correlate with higher deviance (selection vs. socialization unclear)."),
    ("How do adolescents maintain peer ties now?", 
     "Texting/social platforms often surpass face-to-face."),
    ("What are Nesi et al.’s five transformations in social media?", 
     "1. Frequency/immediacy, 2. Amplification, 3. Qualitative change, 4. Compensatory opportunities, 5. Novel behaviors."),
    ("When does peer pressure peak?", 
     "8th–9th grade, esp. antisocial norms."),
    ("When is conformity heightened?", 
     "Uncertain identity, higher-status peer present."),
    ("What gender nuance in conformity?", 
     "Boys more susceptible to sexual pressure in some studies."),
    ("What links to substance use in middle school?", 
     "Peer pressure."),
    ("What are cliques?", 
     "Small (5–6), same-age/sex; activity/friendship-based; strong in-group."),
    ("What are crowds?", 
     "Larger, reputation-based (e.g., jocks); members may not interact."),
    ("What differ by crowd?", 
     "Risk profiles (some link to substance/violence/depression/suicide/inactivity/obesity)."),
    ("What contrast between cliques and crowds?", 
     "Intimacy vs. reputation/identity signaling."),
    ("What happened during pandemic to peers?", 
     "Isolation increased; social media buffered for some."),
    ("What is stage 1 of romantic trajectory (11–13)?", 
     "Attractions/affiliations (crushes, group settings)."),
    ("What is stage 2 (14–16)?", 
     "Exploration—casual/group dating; peers as go-betweens."),
    ("What is stage 3 (17–19)?", 
     "Consolidating dyadic bonds—stable, adult-like (~1 year+)."),
    ("What about early bloomers (11–13)?", 
     "Higher externalizing over time vs. on-time/late."),
    ("What are late bloomers?", 
     "Minority at 17–19 with limited/no experience."),
    ("How do relationship qualities change?", 
     "Short-term more supportive in late adolescence; long-term supportive but turbulent."),
    ("What patterns for sexual minority youth?", 
     "Other-sex dating for clarification/concealment; diverse later orientations."),
    ("How do sociocultural contexts shape romance?", 
     "Values/religion/traditions on age, freedom, chaperoning, gender."),
    ("What norms for Latino/Asian American?", 
     "More conservative vs. Anglo-American."),
    ("What can acculturation gaps cause?", 
     "Parent–adolescent conflict (e.g., unchaperoned dating in Mexican American)."),
    ("What links to more romantic experience?", 
     "Higher competence but also substance/delinquency/sexual behavior."),
    ("What associates with early dating?", 
     "Depression (esp. girls), pregnancy, school/home problems."),
    ("What buffers in romance?", 
     "Supportive ties offset negative maternal; early disclosure predicts companionship; friendship conflict predicts lower."),
    ("How does culture shape adolescent health?", 
     "Mortality from disease/malnutrition declined; health-compromising behaviors increased in some."),
    ("What about gender in cross-cultural comparisons?", 
     "Males greater education/sexual freedom beyond Japan/Philippines/West; gaps narrowing."),
    ("What family variations cross-culturally?", 
     "Tight extended-kin (Arab) vs. less authoritarian/divorce (U.S./West)."),
    ("What global shifts in families?", 
     "Urban migration, smaller families, less extended households, more maternal employment."),
    ("How do peers differ cross-culturally?", 
     "Western: peers take parental roles; constraints for girls in Arab; street youth peers as surrogate (South America)."),
    ("What are rites of passage?", 
     "Ceremonies marking transition to adulthood."),
    ("What functions of rites?", 
     "Separation, ritual death/rebirth, sacred knowledge; bonds with adults."),
    ("Where are rites historically rich?", 
     "Sub-Saharan Africa; decline with industrialization/schooling."),
    ("What U.S. parallels to rites?", 
     "Religious (bar mitzvah, confirmation), social debuts, high school graduation."),
    ("What risks with low SES?", 
     "Lower achievement/occupation, reduced cortical surface, weaker memory, smoking/depression/delinquency, CVD."),
    ("What about lifespan cognition and low SES?", 
     "Lower function, steeper decline in mid/late adulthood."),
    ("What about physical fitness and SES?", 
     "Lower in low-SES youth."),
    ("Why does timing of poverty matter?", 
     "Persistent/early (birth–2) predicts lowest well-being; each year adds risk."),
    ("What protective factors for low SES?", 
     "Academic commitment, emotional control, family involvement, supportive school → higher GPA."),
    ("What stressors for immigrant youth?", 
     "Language, network disruption, acculturation vs. identity, SES changes, undocumented status."),
    ("What is needed for immigrants?", 
     "Culturally sensitive interventions."),
    ("What heterogeneity in ethnic minority families?", 
     "Vary by nativity, time in U.S., SES, values, parenting, origin."),
    ("What in Mexican-origin youth?", 
     "Familism = lower risk taking."),
    ("What predicts children's achievement?", 
     "Parents’ pre-migration education."),
    ("How are ethnicity and SES confounded?", 
     "Minorities overrepresented in low SES; many 'ethnic effects' are SES."),
    ("What is double disadvantage for minorities?", 
     "Prejudice/discrimination + poverty stressors."),
    ("What current contexts for minorities?", 
     "BLM, deaths; families provide socialization (coping, safety, pride)."),
    ("What trends in media use?", 
     "Jump in early adolescence; smartphone surge 2000s–2010s; texting/social > face-to-face."),
    ("What links to more screen time?", 
     "Lower achievement (English/math)."),
    ("What about nighttime phone use (13–16)?", 
     "Worse sleep, higher externalizing, lower self-esteem/coping."),
    ("What gender differences in media?", 
     "Girls more smartphone/social/texting/computer; boys more gaming."),
    ("What about heavy users?", 
     "~2x likely low well-being."),
    ("What does parental media monitoring lead to?", 
     "More sleep, better school, less aggression, more prosocial; monitoring violence = lower aggression."),
    ("What is media multitasking?", 
     "Inflates exposure (double-digit hours/day for tweens/teens)."),
    ("What links to heavier multitasking?", 
     "Worse social well-being, higher depression/anxiety, less delay gratification, more intuitive errors, lower EF/memory/language/math."),
    ("What is a juvenile delinquent?", 
     "Adolescent who breaks law/engages illegally; records underestimate."),
    ("What trends in U.S. delinquency cases?", 
     "Declined 2010–2017, but higher than 1960."),
    ("What gender in delinquency?", 
     "Males > females; female share increased."),
    ("What disparities in delinquency?", 
     "Higher low-SES/minority; biases/inequities affect rates."),
    ("What does delinquency predict?", 
     "Poorer adult outcomes (unemployment)."),
    ("What individual factors in delinquency?", 
     "Low self-control/intelligence/attention; callous traits (males)."),
    ("What identity factor (Erikson)?", 
     "Negative identity when legitimate roles inaccessible."),
    ("What family factors in delinquency?", 
     "Poverty, maltreatment, low monitoring, non-authoritative, sibling, conflict."),
    ("What peers/school factors?", 
     "Delinquent peers/classrooms, low academic, learning disabilities."),
    ("What neighborhood/SES factors?", 
     "Antisocial norms, repeated poverty."),
    ("What protects against delinquency?", 
     "Monitoring, authoritative parenting, school engagement, academic support."),
    ("What treatment for delinquency?", 
     "Family therapy effective."),
    ("What prevalence of lifetime MDD in adolescence?", 
     "15–20%."),
    ("What risk markers for depression?", 
     "High stress/loss/hopelessness, low self-esteem, poor emotion management, interpersonal stress (girls)."),
    ("What barriers to help-seeking?", 
     "Low recognition, informal supports, stigma."),
    ("When does gender difference in depression emerge?", 
     "By 12–17; higher in females."),
    ("Why higher depression in females?", 
     "Rumination, negative body/image, discrimination, earlier puberty/cumulative stress."),
    ("What long-term sequelae of adolescent depression?", 
     "Recurrence, stronger symptoms, migraine, poor health/support into 20s; MH problems, relationship/education issues."),
    ("What etiology for depression?", 
     "Gene × environment × relationships."),
    ("What genetic factors in depression?", 
     "Dopamine/serotonin polymorphisms (e.g., 5-HTTLPR short) interact with stress."),
    ("What family factors in depression?", 
     "Depressed parent, unavailability, marital conflict, financial strain; co-rumination with mothers."),
    ("What peers/romance factors?", 
     "Lack best-friend, rejection, friends’ depression, co-rumination (girls), romantic stress."),
    ("What treatments for depression?", 
     "CBT, interpersonal therapy, SSRIs; combination best for moderate-severe."),
    ("What about family therapy for depression?", 
     "Supportive evidence."),
    ("When does suicide rise?", 
     "Adolescence, again emerging adulthood."),
    ("What is suicide's rank in adolescent death?", 
     "Second after accidents; rates increased 2007–2017."),
    ("What variation in suicide?", 
     "Cross-national substantial."),
    ("What about attempts vs. deaths?", 
     "More ideators/attempters; females attempt more, males die more (lethal means); gap narrowed."),
    ("What strongest correlate of suicide?", 
     "Depression; hopelessness key."),
    ("What genetic in suicide?", 
     "Familial aggregation."),
    ("What adversity in suicide?", 
     "Family discord, negative parents; maltreatment/sexual abuse."),
    ("What acute stressors?", 
     "School failure, discipline, breakups, recent events."),
    ("What links to suicidal thoughts/attempts?", 
     "Bullying/cyberbullying across countries."),
    ("What are the 'big four' problem behaviors?", 
     "Drug abuse, delinquency, sexual problems, school problems; often cluster."),
    ("What links to heavy substance use?", 
     "Early sex, low grades, dropout, delinquency."),
    ("What links to early sexual initiation?", 
     "Tobacco/alcohol/marijuana, delinquency, lower grades."),
    ("What links to delinquency?", 
     "Early sex/pregnancy, substance, dropout."),
    ("What fraction engage in multiple problems?", 
     "Notable minority."),
    ("What component of effective prevention?", 
     "Intensive individualized attention (mentor, tailored goals, referrals)."),
    ("What another component?", 
     "Community-wide collaboration (curricula + media + services + enforcement + programs)."),
    ("What third component?", 
     "Early identification/intervention (childhood/early adolescence/families; at onset)."),
    ("What model example of prevention?", 
     "Perry Preschool (early education + visits) = reduced arrests/dropout, improved competence.")
]

current_index = 0
showing_answer = False  

# Auto font resize
def resize_text(event=None):
    """Dynamically resize text to fit inside card_label without overflow."""
    max_width = card_frame.winfo_width() - 20
    max_height = card_frame.winfo_height() - 20
    text = card_text.get()

    # Start with a reasonably large font
    size = 32
    f = tkfont.Font(family="Arial", size=size)

    # Reduce font size until text fits both width and height
    while (f.measure(text) > max_width or f.metrics("linespace") * text.count("\n") > max_height) and size > 8:
        size -= 1
        f.configure(size=size)
    card_label.config(font=f)

# GUI functions
def flip_card():
    global showing_answer
    showing_answer = not showing_answer
    if showing_answer:
        card_text.set(flashcards[current_index][1])
    else:
        card_text.set(flashcards[current_index][0])
    flip_button.config(text="Flip")
    resize_text()

def next_card():
    global current_index, showing_answer
    current_index = (current_index + 1) % len(flashcards)
    showing_answer = False
    card_text.set(flashcards[current_index][0])
    flip_button.config(text="Flip")
    resize_text()

def previous_card():
    global current_index, showing_answer
    current_index = (current_index - 1) % len(flashcards)  # Wrap around to last card if at the first
    showing_answer = False
    card_text.set(flashcards[current_index][0])
    flip_button.config(text="Flip")
    resize_text()

# GUI setup
root = tk.Tk()
root.title("Flashcards - Developmental Psychology")
root.geometry("650x400")
root.config(bg="#f0f0f0")

card_text = tk.StringVar()
card_text.set(flashcards[current_index][0])

card_frame = tk.Frame(root, bg="white", bd=2, relief="raised", width=500, height=250)
card_frame.pack(pady=50)
card_frame.pack_propagate(False) 

card_label = tk.Label(card_frame, textvariable=card_text, wraplength=480, bg="white", justify="center")
card_label.pack(expand=True, fill="both", padx=10, pady=10)

# Buttons
button_frame = tk.Frame(root, bg="#f0f0f0")
button_frame.pack(pady=10)

previous_button = tk.Button(button_frame, text="Previous Card", command=previous_card, width=15, height=2, bg="#FF9800", fg="white", font=("Arial", 12))
previous_button.pack(side="left", padx=10)

flip_button = tk.Button(button_frame, text="Flip", command=flip_card, width=15, height=2, bg="#4CAF50", fg="white", font=("Arial", 12))
flip_button.pack(side="left", padx=10)

next_button = tk.Button(button_frame, text="Next Card", command=next_card, width=15, height=2, bg="#2196F3", fg="white", font=("Arial", 12))
next_button.pack(side="left", padx=10)

# Bind resizing so text adjusts when window size changes
card_frame.bind("<Configure>", resize_text)

# Initial adjustment
root.after(100, resize_text)

root.mainloop()
